name: Build Package
run-name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: run build

      - name: Run lint
        continue-on-error: true
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: run test

      - name: Run e2e tests
        continue-on-error: true
        uses: borales/actions-yarn@v4
        with:
          cmd: run start
